PUT http://localhost:3003/api/blogs/61e854b57ea8de7f8146dcef
Content-Type: application/json

{
    "title": "God Emperor of Dune",
    "author": "Frank Herbert",
    "url": "dune.com",
    "likes": 50
}