POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pc2hlZWwiLCJpZCI6IjYxZjAxZmMxYWZmMmI5MWU1ZWRhOWZhMSIsImlhdCI6MTY0MzEyNjg4MX0.q-bfgqvpL727LFEz9N0nEEs3oyyvclrsl3lAdUPiIPs

{
    "author": "bujord",
    "title": "vorkisagen",
    "url": "miles.com",
    "likes": 10,
    "userId": "61f01fc1aff2b91e5eda9fa1"
}